# Generated by Django 5.1.6 on 2025-02-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_articlemodel_status_alter_articlemodel_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
